// Code generated by go-swagger; DO NOT EDIT.

package firewall

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cohesity/go-sdk/v2/models"
)

// NewUpdateFirewallSettingsParams creates a new UpdateFirewallSettingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateFirewallSettingsParams() *UpdateFirewallSettingsParams {
	return &UpdateFirewallSettingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateFirewallSettingsParamsWithTimeout creates a new UpdateFirewallSettingsParams object
// with the ability to set a timeout on a request.
func NewUpdateFirewallSettingsParamsWithTimeout(timeout time.Duration) *UpdateFirewallSettingsParams {
	return &UpdateFirewallSettingsParams{
		timeout: timeout,
	}
}

// NewUpdateFirewallSettingsParamsWithContext creates a new UpdateFirewallSettingsParams object
// with the ability to set a context for a request.
func NewUpdateFirewallSettingsParamsWithContext(ctx context.Context) *UpdateFirewallSettingsParams {
	return &UpdateFirewallSettingsParams{
		Context: ctx,
	}
}

// NewUpdateFirewallSettingsParamsWithHTTPClient creates a new UpdateFirewallSettingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateFirewallSettingsParamsWithHTTPClient(client *http.Client) *UpdateFirewallSettingsParams {
	return &UpdateFirewallSettingsParams{
		HTTPClient: client,
	}
}

/*
UpdateFirewallSettingsParams contains all the parameters to send to the API endpoint

	for the update firewall settings operation.

	Typically these are written to a http.Request.
*/
type UpdateFirewallSettingsParams struct {

	/* Body.

	   Specifies the parameters to configure firewall settings.
	*/
	Body *models.UpdateFirewallRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update firewall settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateFirewallSettingsParams) WithDefaults() *UpdateFirewallSettingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update firewall settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateFirewallSettingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update firewall settings params
func (o *UpdateFirewallSettingsParams) WithTimeout(timeout time.Duration) *UpdateFirewallSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update firewall settings params
func (o *UpdateFirewallSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update firewall settings params
func (o *UpdateFirewallSettingsParams) WithContext(ctx context.Context) *UpdateFirewallSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update firewall settings params
func (o *UpdateFirewallSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update firewall settings params
func (o *UpdateFirewallSettingsParams) WithHTTPClient(client *http.Client) *UpdateFirewallSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update firewall settings params
func (o *UpdateFirewallSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update firewall settings params
func (o *UpdateFirewallSettingsParams) WithBody(body *models.UpdateFirewallRequest) *UpdateFirewallSettingsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update firewall settings params
func (o *UpdateFirewallSettingsParams) SetBody(body *models.UpdateFirewallRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateFirewallSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
