/*
Cohesity REST API

Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MssqlNativeObjectProtection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MssqlNativeObjectProtection{}

// MssqlNativeObjectProtection Specifies the object params to create Native based MSSQL Object Protection.
type MssqlNativeObjectProtection struct {
	// Specifies the ID of the object being protected. If this is a non leaf level object, then the object will be auto-protected unless leaf objects are specified for exclusion.
	Id NullableInt64 `json:"id"`
}

type _MssqlNativeObjectProtection MssqlNativeObjectProtection

// NewMssqlNativeObjectProtection instantiates a new MssqlNativeObjectProtection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMssqlNativeObjectProtection(id NullableInt64) *MssqlNativeObjectProtection {
	this := MssqlNativeObjectProtection{}
	this.Id = id
	return &this
}

// NewMssqlNativeObjectProtectionWithDefaults instantiates a new MssqlNativeObjectProtection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMssqlNativeObjectProtectionWithDefaults() *MssqlNativeObjectProtection {
	this := MssqlNativeObjectProtection{}
	return &this
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *MssqlNativeObjectProtection) GetId() int64 {
	if o == nil || o.Id.Get() == nil {
		var ret int64
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MssqlNativeObjectProtection) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *MssqlNativeObjectProtection) SetId(v int64) {
	o.Id.Set(&v)
}

func (o MssqlNativeObjectProtection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MssqlNativeObjectProtection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id.Get()
	return toSerialize, nil
}

func (o *MssqlNativeObjectProtection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMssqlNativeObjectProtection := _MssqlNativeObjectProtection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMssqlNativeObjectProtection)

	if err != nil {
		return err
	}

	*o = MssqlNativeObjectProtection(varMssqlNativeObjectProtection)

	return err
}

type NullableMssqlNativeObjectProtection struct {
	value *MssqlNativeObjectProtection
	isSet bool
}

func (v NullableMssqlNativeObjectProtection) Get() *MssqlNativeObjectProtection {
	return v.value
}

func (v *NullableMssqlNativeObjectProtection) Set(val *MssqlNativeObjectProtection) {
	v.value = val
	v.isSet = true
}

func (v NullableMssqlNativeObjectProtection) IsSet() bool {
	return v.isSet
}

func (v *NullableMssqlNativeObjectProtection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMssqlNativeObjectProtection(val *MssqlNativeObjectProtection) *NullableMssqlNativeObjectProtection {
	return &NullableMssqlNativeObjectProtection{value: val, isSet: true}
}

func (v NullableMssqlNativeObjectProtection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMssqlNativeObjectProtection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


