/*
Cohesity REST API

Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the AwsObjectProtectionRequestParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsObjectProtectionRequestParams{}

// AwsObjectProtectionRequestParams Specifies the parameters which are specific to AWS related Object Protection.
type AwsObjectProtectionRequestParams struct {
	// Specifies the AWS Protection Job type.
	ProtectionType *string `json:"protectionType,omitempty"`
	AuroraSnapshotManagerProtectionTypeParams *AwsAuroraSnapshotManagerObjectProtectionParams `json:"auroraSnapshotManagerProtectionTypeParams,omitempty"`
	DynamoDBProtectionTypeParams *AwsDynamoDBProtectionParams `json:"dynamoDBProtectionTypeParams,omitempty"`
	NativeProtectionTypeParams *AwsNativeObjectProtectionParams `json:"nativeProtectionTypeParams,omitempty"`
	RdsPostgresProtectionTypeParams *AwsRdsPostgresProtectionParams `json:"rdsPostgresProtectionTypeParams,omitempty"`
	RdsSnapshotManagerProtectionTypeParams *AwsRdsSnapshotManagerObjectProtectionParams `json:"rdsSnapshotManagerProtectionTypeParams,omitempty"`
	S3ProtectionTypeParams *AwsS3ProtectionParams `json:"s3ProtectionTypeParams,omitempty"`
	SnapshotManagerProtectionTypeParams *AwsSnapshotManagerObjectProtectionParams `json:"snapshotManagerProtectionTypeParams,omitempty"`
}

// NewAwsObjectProtectionRequestParams instantiates a new AwsObjectProtectionRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsObjectProtectionRequestParams() *AwsObjectProtectionRequestParams {
	this := AwsObjectProtectionRequestParams{}
	return &this
}

// NewAwsObjectProtectionRequestParamsWithDefaults instantiates a new AwsObjectProtectionRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsObjectProtectionRequestParamsWithDefaults() *AwsObjectProtectionRequestParams {
	this := AwsObjectProtectionRequestParams{}
	return &this
}

// GetProtectionType returns the ProtectionType field value if set, zero value otherwise.
func (o *AwsObjectProtectionRequestParams) GetProtectionType() string {
	if o == nil || IsNil(o.ProtectionType) {
		var ret string
		return ret
	}
	return *o.ProtectionType
}

// GetProtectionTypeOk returns a tuple with the ProtectionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsObjectProtectionRequestParams) GetProtectionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ProtectionType) {
		return nil, false
	}
	return o.ProtectionType, true
}

// HasProtectionType returns a boolean if a field has been set.
func (o *AwsObjectProtectionRequestParams) HasProtectionType() bool {
	if o != nil && !IsNil(o.ProtectionType) {
		return true
	}

	return false
}

// SetProtectionType gets a reference to the given string and assigns it to the ProtectionType field.
func (o *AwsObjectProtectionRequestParams) SetProtectionType(v string) {
	o.ProtectionType = &v
}

// GetAuroraSnapshotManagerProtectionTypeParams returns the AuroraSnapshotManagerProtectionTypeParams field value if set, zero value otherwise.
func (o *AwsObjectProtectionRequestParams) GetAuroraSnapshotManagerProtectionTypeParams() AwsAuroraSnapshotManagerObjectProtectionParams {
	if o == nil || IsNil(o.AuroraSnapshotManagerProtectionTypeParams) {
		var ret AwsAuroraSnapshotManagerObjectProtectionParams
		return ret
	}
	return *o.AuroraSnapshotManagerProtectionTypeParams
}

// GetAuroraSnapshotManagerProtectionTypeParamsOk returns a tuple with the AuroraSnapshotManagerProtectionTypeParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsObjectProtectionRequestParams) GetAuroraSnapshotManagerProtectionTypeParamsOk() (*AwsAuroraSnapshotManagerObjectProtectionParams, bool) {
	if o == nil || IsNil(o.AuroraSnapshotManagerProtectionTypeParams) {
		return nil, false
	}
	return o.AuroraSnapshotManagerProtectionTypeParams, true
}

// HasAuroraSnapshotManagerProtectionTypeParams returns a boolean if a field has been set.
func (o *AwsObjectProtectionRequestParams) HasAuroraSnapshotManagerProtectionTypeParams() bool {
	if o != nil && !IsNil(o.AuroraSnapshotManagerProtectionTypeParams) {
		return true
	}

	return false
}

// SetAuroraSnapshotManagerProtectionTypeParams gets a reference to the given AwsAuroraSnapshotManagerObjectProtectionParams and assigns it to the AuroraSnapshotManagerProtectionTypeParams field.
func (o *AwsObjectProtectionRequestParams) SetAuroraSnapshotManagerProtectionTypeParams(v AwsAuroraSnapshotManagerObjectProtectionParams) {
	o.AuroraSnapshotManagerProtectionTypeParams = &v
}

// GetDynamoDBProtectionTypeParams returns the DynamoDBProtectionTypeParams field value if set, zero value otherwise.
func (o *AwsObjectProtectionRequestParams) GetDynamoDBProtectionTypeParams() AwsDynamoDBProtectionParams {
	if o == nil || IsNil(o.DynamoDBProtectionTypeParams) {
		var ret AwsDynamoDBProtectionParams
		return ret
	}
	return *o.DynamoDBProtectionTypeParams
}

// GetDynamoDBProtectionTypeParamsOk returns a tuple with the DynamoDBProtectionTypeParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsObjectProtectionRequestParams) GetDynamoDBProtectionTypeParamsOk() (*AwsDynamoDBProtectionParams, bool) {
	if o == nil || IsNil(o.DynamoDBProtectionTypeParams) {
		return nil, false
	}
	return o.DynamoDBProtectionTypeParams, true
}

// HasDynamoDBProtectionTypeParams returns a boolean if a field has been set.
func (o *AwsObjectProtectionRequestParams) HasDynamoDBProtectionTypeParams() bool {
	if o != nil && !IsNil(o.DynamoDBProtectionTypeParams) {
		return true
	}

	return false
}

// SetDynamoDBProtectionTypeParams gets a reference to the given AwsDynamoDBProtectionParams and assigns it to the DynamoDBProtectionTypeParams field.
func (o *AwsObjectProtectionRequestParams) SetDynamoDBProtectionTypeParams(v AwsDynamoDBProtectionParams) {
	o.DynamoDBProtectionTypeParams = &v
}

// GetNativeProtectionTypeParams returns the NativeProtectionTypeParams field value if set, zero value otherwise.
func (o *AwsObjectProtectionRequestParams) GetNativeProtectionTypeParams() AwsNativeObjectProtectionParams {
	if o == nil || IsNil(o.NativeProtectionTypeParams) {
		var ret AwsNativeObjectProtectionParams
		return ret
	}
	return *o.NativeProtectionTypeParams
}

// GetNativeProtectionTypeParamsOk returns a tuple with the NativeProtectionTypeParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsObjectProtectionRequestParams) GetNativeProtectionTypeParamsOk() (*AwsNativeObjectProtectionParams, bool) {
	if o == nil || IsNil(o.NativeProtectionTypeParams) {
		return nil, false
	}
	return o.NativeProtectionTypeParams, true
}

// HasNativeProtectionTypeParams returns a boolean if a field has been set.
func (o *AwsObjectProtectionRequestParams) HasNativeProtectionTypeParams() bool {
	if o != nil && !IsNil(o.NativeProtectionTypeParams) {
		return true
	}

	return false
}

// SetNativeProtectionTypeParams gets a reference to the given AwsNativeObjectProtectionParams and assigns it to the NativeProtectionTypeParams field.
func (o *AwsObjectProtectionRequestParams) SetNativeProtectionTypeParams(v AwsNativeObjectProtectionParams) {
	o.NativeProtectionTypeParams = &v
}

// GetRdsPostgresProtectionTypeParams returns the RdsPostgresProtectionTypeParams field value if set, zero value otherwise.
func (o *AwsObjectProtectionRequestParams) GetRdsPostgresProtectionTypeParams() AwsRdsPostgresProtectionParams {
	if o == nil || IsNil(o.RdsPostgresProtectionTypeParams) {
		var ret AwsRdsPostgresProtectionParams
		return ret
	}
	return *o.RdsPostgresProtectionTypeParams
}

// GetRdsPostgresProtectionTypeParamsOk returns a tuple with the RdsPostgresProtectionTypeParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsObjectProtectionRequestParams) GetRdsPostgresProtectionTypeParamsOk() (*AwsRdsPostgresProtectionParams, bool) {
	if o == nil || IsNil(o.RdsPostgresProtectionTypeParams) {
		return nil, false
	}
	return o.RdsPostgresProtectionTypeParams, true
}

// HasRdsPostgresProtectionTypeParams returns a boolean if a field has been set.
func (o *AwsObjectProtectionRequestParams) HasRdsPostgresProtectionTypeParams() bool {
	if o != nil && !IsNil(o.RdsPostgresProtectionTypeParams) {
		return true
	}

	return false
}

// SetRdsPostgresProtectionTypeParams gets a reference to the given AwsRdsPostgresProtectionParams and assigns it to the RdsPostgresProtectionTypeParams field.
func (o *AwsObjectProtectionRequestParams) SetRdsPostgresProtectionTypeParams(v AwsRdsPostgresProtectionParams) {
	o.RdsPostgresProtectionTypeParams = &v
}

// GetRdsSnapshotManagerProtectionTypeParams returns the RdsSnapshotManagerProtectionTypeParams field value if set, zero value otherwise.
func (o *AwsObjectProtectionRequestParams) GetRdsSnapshotManagerProtectionTypeParams() AwsRdsSnapshotManagerObjectProtectionParams {
	if o == nil || IsNil(o.RdsSnapshotManagerProtectionTypeParams) {
		var ret AwsRdsSnapshotManagerObjectProtectionParams
		return ret
	}
	return *o.RdsSnapshotManagerProtectionTypeParams
}

// GetRdsSnapshotManagerProtectionTypeParamsOk returns a tuple with the RdsSnapshotManagerProtectionTypeParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsObjectProtectionRequestParams) GetRdsSnapshotManagerProtectionTypeParamsOk() (*AwsRdsSnapshotManagerObjectProtectionParams, bool) {
	if o == nil || IsNil(o.RdsSnapshotManagerProtectionTypeParams) {
		return nil, false
	}
	return o.RdsSnapshotManagerProtectionTypeParams, true
}

// HasRdsSnapshotManagerProtectionTypeParams returns a boolean if a field has been set.
func (o *AwsObjectProtectionRequestParams) HasRdsSnapshotManagerProtectionTypeParams() bool {
	if o != nil && !IsNil(o.RdsSnapshotManagerProtectionTypeParams) {
		return true
	}

	return false
}

// SetRdsSnapshotManagerProtectionTypeParams gets a reference to the given AwsRdsSnapshotManagerObjectProtectionParams and assigns it to the RdsSnapshotManagerProtectionTypeParams field.
func (o *AwsObjectProtectionRequestParams) SetRdsSnapshotManagerProtectionTypeParams(v AwsRdsSnapshotManagerObjectProtectionParams) {
	o.RdsSnapshotManagerProtectionTypeParams = &v
}

// GetS3ProtectionTypeParams returns the S3ProtectionTypeParams field value if set, zero value otherwise.
func (o *AwsObjectProtectionRequestParams) GetS3ProtectionTypeParams() AwsS3ProtectionParams {
	if o == nil || IsNil(o.S3ProtectionTypeParams) {
		var ret AwsS3ProtectionParams
		return ret
	}
	return *o.S3ProtectionTypeParams
}

// GetS3ProtectionTypeParamsOk returns a tuple with the S3ProtectionTypeParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsObjectProtectionRequestParams) GetS3ProtectionTypeParamsOk() (*AwsS3ProtectionParams, bool) {
	if o == nil || IsNil(o.S3ProtectionTypeParams) {
		return nil, false
	}
	return o.S3ProtectionTypeParams, true
}

// HasS3ProtectionTypeParams returns a boolean if a field has been set.
func (o *AwsObjectProtectionRequestParams) HasS3ProtectionTypeParams() bool {
	if o != nil && !IsNil(o.S3ProtectionTypeParams) {
		return true
	}

	return false
}

// SetS3ProtectionTypeParams gets a reference to the given AwsS3ProtectionParams and assigns it to the S3ProtectionTypeParams field.
func (o *AwsObjectProtectionRequestParams) SetS3ProtectionTypeParams(v AwsS3ProtectionParams) {
	o.S3ProtectionTypeParams = &v
}

// GetSnapshotManagerProtectionTypeParams returns the SnapshotManagerProtectionTypeParams field value if set, zero value otherwise.
func (o *AwsObjectProtectionRequestParams) GetSnapshotManagerProtectionTypeParams() AwsSnapshotManagerObjectProtectionParams {
	if o == nil || IsNil(o.SnapshotManagerProtectionTypeParams) {
		var ret AwsSnapshotManagerObjectProtectionParams
		return ret
	}
	return *o.SnapshotManagerProtectionTypeParams
}

// GetSnapshotManagerProtectionTypeParamsOk returns a tuple with the SnapshotManagerProtectionTypeParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsObjectProtectionRequestParams) GetSnapshotManagerProtectionTypeParamsOk() (*AwsSnapshotManagerObjectProtectionParams, bool) {
	if o == nil || IsNil(o.SnapshotManagerProtectionTypeParams) {
		return nil, false
	}
	return o.SnapshotManagerProtectionTypeParams, true
}

// HasSnapshotManagerProtectionTypeParams returns a boolean if a field has been set.
func (o *AwsObjectProtectionRequestParams) HasSnapshotManagerProtectionTypeParams() bool {
	if o != nil && !IsNil(o.SnapshotManagerProtectionTypeParams) {
		return true
	}

	return false
}

// SetSnapshotManagerProtectionTypeParams gets a reference to the given AwsSnapshotManagerObjectProtectionParams and assigns it to the SnapshotManagerProtectionTypeParams field.
func (o *AwsObjectProtectionRequestParams) SetSnapshotManagerProtectionTypeParams(v AwsSnapshotManagerObjectProtectionParams) {
	o.SnapshotManagerProtectionTypeParams = &v
}

func (o AwsObjectProtectionRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsObjectProtectionRequestParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProtectionType) {
		toSerialize["protectionType"] = o.ProtectionType
	}
	if !IsNil(o.AuroraSnapshotManagerProtectionTypeParams) {
		toSerialize["auroraSnapshotManagerProtectionTypeParams"] = o.AuroraSnapshotManagerProtectionTypeParams
	}
	if !IsNil(o.DynamoDBProtectionTypeParams) {
		toSerialize["dynamoDBProtectionTypeParams"] = o.DynamoDBProtectionTypeParams
	}
	if !IsNil(o.NativeProtectionTypeParams) {
		toSerialize["nativeProtectionTypeParams"] = o.NativeProtectionTypeParams
	}
	if !IsNil(o.RdsPostgresProtectionTypeParams) {
		toSerialize["rdsPostgresProtectionTypeParams"] = o.RdsPostgresProtectionTypeParams
	}
	if !IsNil(o.RdsSnapshotManagerProtectionTypeParams) {
		toSerialize["rdsSnapshotManagerProtectionTypeParams"] = o.RdsSnapshotManagerProtectionTypeParams
	}
	if !IsNil(o.S3ProtectionTypeParams) {
		toSerialize["s3ProtectionTypeParams"] = o.S3ProtectionTypeParams
	}
	if !IsNil(o.SnapshotManagerProtectionTypeParams) {
		toSerialize["snapshotManagerProtectionTypeParams"] = o.SnapshotManagerProtectionTypeParams
	}
	return toSerialize, nil
}

type NullableAwsObjectProtectionRequestParams struct {
	value *AwsObjectProtectionRequestParams
	isSet bool
}

func (v NullableAwsObjectProtectionRequestParams) Get() *AwsObjectProtectionRequestParams {
	return v.value
}

func (v *NullableAwsObjectProtectionRequestParams) Set(val *AwsObjectProtectionRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsObjectProtectionRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsObjectProtectionRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsObjectProtectionRequestParams(val *AwsObjectProtectionRequestParams) *NullableAwsObjectProtectionRequestParams {
	return &NullableAwsObjectProtectionRequestParams{value: val, isSet: true}
}

func (v NullableAwsObjectProtectionRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsObjectProtectionRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


