/*
Cohesity REST API

Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecoverKvmVmNewSourceConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecoverKvmVmNewSourceConfig{}

// RecoverKvmVmNewSourceConfig Specifies the new destination Source configuration where the VMs will be recovered.
type RecoverKvmVmNewSourceConfig struct {
	Cluster RecoverKvmVmNewSourceConfigCluster `json:"cluster"`
	DataCenter RecoverKvmVmNewSourceConfigDataCenter `json:"dataCenter"`
	NetworkConfig *RecoverKvmVmNewSourceConfigNetworkConfig `json:"networkConfig,omitempty"`
	Source RecoverKvmVmNewSourceConfigSource `json:"source"`
	StorageDomain RecoverKvmVmNewSourceConfigStorageDomain `json:"storageDomain"`
}

type _RecoverKvmVmNewSourceConfig RecoverKvmVmNewSourceConfig

// NewRecoverKvmVmNewSourceConfig instantiates a new RecoverKvmVmNewSourceConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecoverKvmVmNewSourceConfig(cluster RecoverKvmVmNewSourceConfigCluster, dataCenter RecoverKvmVmNewSourceConfigDataCenter, source RecoverKvmVmNewSourceConfigSource, storageDomain RecoverKvmVmNewSourceConfigStorageDomain) *RecoverKvmVmNewSourceConfig {
	this := RecoverKvmVmNewSourceConfig{}
	this.Cluster = cluster
	this.DataCenter = dataCenter
	this.Source = source
	this.StorageDomain = storageDomain
	return &this
}

// NewRecoverKvmVmNewSourceConfigWithDefaults instantiates a new RecoverKvmVmNewSourceConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecoverKvmVmNewSourceConfigWithDefaults() *RecoverKvmVmNewSourceConfig {
	this := RecoverKvmVmNewSourceConfig{}
	return &this
}

// GetCluster returns the Cluster field value
func (o *RecoverKvmVmNewSourceConfig) GetCluster() RecoverKvmVmNewSourceConfigCluster {
	if o == nil {
		var ret RecoverKvmVmNewSourceConfigCluster
		return ret
	}

	return o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value
// and a boolean to check if the value has been set.
func (o *RecoverKvmVmNewSourceConfig) GetClusterOk() (*RecoverKvmVmNewSourceConfigCluster, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cluster, true
}

// SetCluster sets field value
func (o *RecoverKvmVmNewSourceConfig) SetCluster(v RecoverKvmVmNewSourceConfigCluster) {
	o.Cluster = v
}

// GetDataCenter returns the DataCenter field value
func (o *RecoverKvmVmNewSourceConfig) GetDataCenter() RecoverKvmVmNewSourceConfigDataCenter {
	if o == nil {
		var ret RecoverKvmVmNewSourceConfigDataCenter
		return ret
	}

	return o.DataCenter
}

// GetDataCenterOk returns a tuple with the DataCenter field value
// and a boolean to check if the value has been set.
func (o *RecoverKvmVmNewSourceConfig) GetDataCenterOk() (*RecoverKvmVmNewSourceConfigDataCenter, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataCenter, true
}

// SetDataCenter sets field value
func (o *RecoverKvmVmNewSourceConfig) SetDataCenter(v RecoverKvmVmNewSourceConfigDataCenter) {
	o.DataCenter = v
}

// GetNetworkConfig returns the NetworkConfig field value if set, zero value otherwise.
func (o *RecoverKvmVmNewSourceConfig) GetNetworkConfig() RecoverKvmVmNewSourceConfigNetworkConfig {
	if o == nil || IsNil(o.NetworkConfig) {
		var ret RecoverKvmVmNewSourceConfigNetworkConfig
		return ret
	}
	return *o.NetworkConfig
}

// GetNetworkConfigOk returns a tuple with the NetworkConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecoverKvmVmNewSourceConfig) GetNetworkConfigOk() (*RecoverKvmVmNewSourceConfigNetworkConfig, bool) {
	if o == nil || IsNil(o.NetworkConfig) {
		return nil, false
	}
	return o.NetworkConfig, true
}

// HasNetworkConfig returns a boolean if a field has been set.
func (o *RecoverKvmVmNewSourceConfig) HasNetworkConfig() bool {
	if o != nil && !IsNil(o.NetworkConfig) {
		return true
	}

	return false
}

// SetNetworkConfig gets a reference to the given RecoverKvmVmNewSourceConfigNetworkConfig and assigns it to the NetworkConfig field.
func (o *RecoverKvmVmNewSourceConfig) SetNetworkConfig(v RecoverKvmVmNewSourceConfigNetworkConfig) {
	o.NetworkConfig = &v
}

// GetSource returns the Source field value
func (o *RecoverKvmVmNewSourceConfig) GetSource() RecoverKvmVmNewSourceConfigSource {
	if o == nil {
		var ret RecoverKvmVmNewSourceConfigSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *RecoverKvmVmNewSourceConfig) GetSourceOk() (*RecoverKvmVmNewSourceConfigSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *RecoverKvmVmNewSourceConfig) SetSource(v RecoverKvmVmNewSourceConfigSource) {
	o.Source = v
}

// GetStorageDomain returns the StorageDomain field value
func (o *RecoverKvmVmNewSourceConfig) GetStorageDomain() RecoverKvmVmNewSourceConfigStorageDomain {
	if o == nil {
		var ret RecoverKvmVmNewSourceConfigStorageDomain
		return ret
	}

	return o.StorageDomain
}

// GetStorageDomainOk returns a tuple with the StorageDomain field value
// and a boolean to check if the value has been set.
func (o *RecoverKvmVmNewSourceConfig) GetStorageDomainOk() (*RecoverKvmVmNewSourceConfigStorageDomain, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageDomain, true
}

// SetStorageDomain sets field value
func (o *RecoverKvmVmNewSourceConfig) SetStorageDomain(v RecoverKvmVmNewSourceConfigStorageDomain) {
	o.StorageDomain = v
}

func (o RecoverKvmVmNewSourceConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecoverKvmVmNewSourceConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cluster"] = o.Cluster
	toSerialize["dataCenter"] = o.DataCenter
	if !IsNil(o.NetworkConfig) {
		toSerialize["networkConfig"] = o.NetworkConfig
	}
	toSerialize["source"] = o.Source
	toSerialize["storageDomain"] = o.StorageDomain
	return toSerialize, nil
}

func (o *RecoverKvmVmNewSourceConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cluster",
		"dataCenter",
		"source",
		"storageDomain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecoverKvmVmNewSourceConfig := _RecoverKvmVmNewSourceConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecoverKvmVmNewSourceConfig)

	if err != nil {
		return err
	}

	*o = RecoverKvmVmNewSourceConfig(varRecoverKvmVmNewSourceConfig)

	return err
}

type NullableRecoverKvmVmNewSourceConfig struct {
	value *RecoverKvmVmNewSourceConfig
	isSet bool
}

func (v NullableRecoverKvmVmNewSourceConfig) Get() *RecoverKvmVmNewSourceConfig {
	return v.value
}

func (v *NullableRecoverKvmVmNewSourceConfig) Set(val *RecoverKvmVmNewSourceConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableRecoverKvmVmNewSourceConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableRecoverKvmVmNewSourceConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecoverKvmVmNewSourceConfig(val *RecoverKvmVmNewSourceConfig) *NullableRecoverKvmVmNewSourceConfig {
	return &NullableRecoverKvmVmNewSourceConfig{value: val, isSet: true}
}

func (v NullableRecoverKvmVmNewSourceConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecoverKvmVmNewSourceConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


