/*
Cohesity REST API

Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the LocalUserResponseParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocalUserResponseParams{}

// LocalUserResponseParams Specifies properties for LOCAL cohesity user.
type LocalUserResponseParams struct {
	// Specifies the email address of the User.
	Email NullableString `json:"email,omitempty"`
}

// NewLocalUserResponseParams instantiates a new LocalUserResponseParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalUserResponseParams() *LocalUserResponseParams {
	this := LocalUserResponseParams{}
	return &this
}

// NewLocalUserResponseParamsWithDefaults instantiates a new LocalUserResponseParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalUserResponseParamsWithDefaults() *LocalUserResponseParams {
	this := LocalUserResponseParams{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LocalUserResponseParams) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LocalUserResponseParams) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *LocalUserResponseParams) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *LocalUserResponseParams) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *LocalUserResponseParams) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *LocalUserResponseParams) UnsetEmail() {
	o.Email.Unset()
}

func (o LocalUserResponseParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocalUserResponseParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	return toSerialize, nil
}

type NullableLocalUserResponseParams struct {
	value *LocalUserResponseParams
	isSet bool
}

func (v NullableLocalUserResponseParams) Get() *LocalUserResponseParams {
	return v.value
}

func (v *NullableLocalUserResponseParams) Set(val *LocalUserResponseParams) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalUserResponseParams) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalUserResponseParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalUserResponseParams(val *LocalUserResponseParams) *NullableLocalUserResponseParams {
	return &NullableLocalUserResponseParams{value: val, isSet: true}
}

func (v NullableLocalUserResponseParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalUserResponseParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


