/*
Cohesity REST API

Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HbaseSearchParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HbaseSearchParams{}

// HbaseSearchParams Specifies the parameters which are specific for searching Hbase objects.
type HbaseSearchParams struct {
	// Specifies one or more Hbase object types be searched.
	HbaseObjectTypes []string `json:"hbaseObjectTypes"`
	// Specifies the search string to search the Hbase Objects
	SearchString NullableString `json:"searchString"`
}

type _HbaseSearchParams HbaseSearchParams

// NewHbaseSearchParams instantiates a new HbaseSearchParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHbaseSearchParams(hbaseObjectTypes []string, searchString NullableString) *HbaseSearchParams {
	this := HbaseSearchParams{}
	this.HbaseObjectTypes = hbaseObjectTypes
	this.SearchString = searchString
	return &this
}

// NewHbaseSearchParamsWithDefaults instantiates a new HbaseSearchParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHbaseSearchParamsWithDefaults() *HbaseSearchParams {
	this := HbaseSearchParams{}
	return &this
}

// GetHbaseObjectTypes returns the HbaseObjectTypes field value
func (o *HbaseSearchParams) GetHbaseObjectTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.HbaseObjectTypes
}

// GetHbaseObjectTypesOk returns a tuple with the HbaseObjectTypes field value
// and a boolean to check if the value has been set.
func (o *HbaseSearchParams) GetHbaseObjectTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HbaseObjectTypes, true
}

// SetHbaseObjectTypes sets field value
func (o *HbaseSearchParams) SetHbaseObjectTypes(v []string) {
	o.HbaseObjectTypes = v
}

// GetSearchString returns the SearchString field value
// If the value is explicit nil, the zero value for string will be returned
func (o *HbaseSearchParams) GetSearchString() string {
	if o == nil || o.SearchString.Get() == nil {
		var ret string
		return ret
	}

	return *o.SearchString.Get()
}

// GetSearchStringOk returns a tuple with the SearchString field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HbaseSearchParams) GetSearchStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SearchString.Get(), o.SearchString.IsSet()
}

// SetSearchString sets field value
func (o *HbaseSearchParams) SetSearchString(v string) {
	o.SearchString.Set(&v)
}

func (o HbaseSearchParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HbaseSearchParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hbaseObjectTypes"] = o.HbaseObjectTypes
	toSerialize["searchString"] = o.SearchString.Get()
	return toSerialize, nil
}

func (o *HbaseSearchParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hbaseObjectTypes",
		"searchString",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHbaseSearchParams := _HbaseSearchParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHbaseSearchParams)

	if err != nil {
		return err
	}

	*o = HbaseSearchParams(varHbaseSearchParams)

	return err
}

type NullableHbaseSearchParams struct {
	value *HbaseSearchParams
	isSet bool
}

func (v NullableHbaseSearchParams) Get() *HbaseSearchParams {
	return v.value
}

func (v *NullableHbaseSearchParams) Set(val *HbaseSearchParams) {
	v.value = val
	v.isSet = true
}

func (v NullableHbaseSearchParams) IsSet() bool {
	return v.isSet
}

func (v *NullableHbaseSearchParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHbaseSearchParams(val *HbaseSearchParams) *NullableHbaseSearchParams {
	return &NullableHbaseSearchParams{value: val, isSet: true}
}

func (v NullableHbaseSearchParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHbaseSearchParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


