/*
Cohesity REST API

Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TieringAzureExternalTargetParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TieringAzureExternalTargetParams{}

// TieringAzureExternalTargetParams Specifies the common parameters which are specific to Azure related External Targets.
type TieringAzureExternalTargetParams struct {
	// Specifies the client id of the managed identity assigned to the cluster This is used only for clusters running as Azure VMs where authentication is done using AD.
	ClientId NullableString `json:"clientId,omitempty"`
	// Specifies the container name of the external target.
	ContainerName NullableString `json:"containerName"`
	// Specifies region of the External Target. This is only populated for FortKnox vaults.
	Region NullableString `json:"region,omitempty"`
	// Specifies the storage access key of the external target.
	StorageAccessKey NullableString `json:"storageAccessKey,omitempty"`
	// Specifies the storage account name of the external target.
	StorageAccountName NullableString `json:"storageAccountName"`
	// Specifies the Azure External Target class.
	StorageClass NullableString `json:"storageClass"`
	HotBlobParams *AzureHotBlobParams `json:"hotBlobParams,omitempty"`
}

type _TieringAzureExternalTargetParams TieringAzureExternalTargetParams

// NewTieringAzureExternalTargetParams instantiates a new TieringAzureExternalTargetParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTieringAzureExternalTargetParams(containerName NullableString, storageAccountName NullableString, storageClass NullableString) *TieringAzureExternalTargetParams {
	this := TieringAzureExternalTargetParams{}
	this.ContainerName = containerName
	this.StorageAccountName = storageAccountName
	this.StorageClass = storageClass
	return &this
}

// NewTieringAzureExternalTargetParamsWithDefaults instantiates a new TieringAzureExternalTargetParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTieringAzureExternalTargetParamsWithDefaults() *TieringAzureExternalTargetParams {
	this := TieringAzureExternalTargetParams{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TieringAzureExternalTargetParams) GetClientId() string {
	if o == nil || IsNil(o.ClientId.Get()) {
		var ret string
		return ret
	}
	return *o.ClientId.Get()
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TieringAzureExternalTargetParams) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClientId.Get(), o.ClientId.IsSet()
}

// HasClientId returns a boolean if a field has been set.
func (o *TieringAzureExternalTargetParams) HasClientId() bool {
	if o != nil && o.ClientId.IsSet() {
		return true
	}

	return false
}

// SetClientId gets a reference to the given NullableString and assigns it to the ClientId field.
func (o *TieringAzureExternalTargetParams) SetClientId(v string) {
	o.ClientId.Set(&v)
}
// SetClientIdNil sets the value for ClientId to be an explicit nil
func (o *TieringAzureExternalTargetParams) SetClientIdNil() {
	o.ClientId.Set(nil)
}

// UnsetClientId ensures that no value is present for ClientId, not even an explicit nil
func (o *TieringAzureExternalTargetParams) UnsetClientId() {
	o.ClientId.Unset()
}

// GetContainerName returns the ContainerName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TieringAzureExternalTargetParams) GetContainerName() string {
	if o == nil || o.ContainerName.Get() == nil {
		var ret string
		return ret
	}

	return *o.ContainerName.Get()
}

// GetContainerNameOk returns a tuple with the ContainerName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TieringAzureExternalTargetParams) GetContainerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContainerName.Get(), o.ContainerName.IsSet()
}

// SetContainerName sets field value
func (o *TieringAzureExternalTargetParams) SetContainerName(v string) {
	o.ContainerName.Set(&v)
}

// GetRegion returns the Region field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TieringAzureExternalTargetParams) GetRegion() string {
	if o == nil || IsNil(o.Region.Get()) {
		var ret string
		return ret
	}
	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TieringAzureExternalTargetParams) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// HasRegion returns a boolean if a field has been set.
func (o *TieringAzureExternalTargetParams) HasRegion() bool {
	if o != nil && o.Region.IsSet() {
		return true
	}

	return false
}

// SetRegion gets a reference to the given NullableString and assigns it to the Region field.
func (o *TieringAzureExternalTargetParams) SetRegion(v string) {
	o.Region.Set(&v)
}
// SetRegionNil sets the value for Region to be an explicit nil
func (o *TieringAzureExternalTargetParams) SetRegionNil() {
	o.Region.Set(nil)
}

// UnsetRegion ensures that no value is present for Region, not even an explicit nil
func (o *TieringAzureExternalTargetParams) UnsetRegion() {
	o.Region.Unset()
}

// GetStorageAccessKey returns the StorageAccessKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TieringAzureExternalTargetParams) GetStorageAccessKey() string {
	if o == nil || IsNil(o.StorageAccessKey.Get()) {
		var ret string
		return ret
	}
	return *o.StorageAccessKey.Get()
}

// GetStorageAccessKeyOk returns a tuple with the StorageAccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TieringAzureExternalTargetParams) GetStorageAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageAccessKey.Get(), o.StorageAccessKey.IsSet()
}

// HasStorageAccessKey returns a boolean if a field has been set.
func (o *TieringAzureExternalTargetParams) HasStorageAccessKey() bool {
	if o != nil && o.StorageAccessKey.IsSet() {
		return true
	}

	return false
}

// SetStorageAccessKey gets a reference to the given NullableString and assigns it to the StorageAccessKey field.
func (o *TieringAzureExternalTargetParams) SetStorageAccessKey(v string) {
	o.StorageAccessKey.Set(&v)
}
// SetStorageAccessKeyNil sets the value for StorageAccessKey to be an explicit nil
func (o *TieringAzureExternalTargetParams) SetStorageAccessKeyNil() {
	o.StorageAccessKey.Set(nil)
}

// UnsetStorageAccessKey ensures that no value is present for StorageAccessKey, not even an explicit nil
func (o *TieringAzureExternalTargetParams) UnsetStorageAccessKey() {
	o.StorageAccessKey.Unset()
}

// GetStorageAccountName returns the StorageAccountName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TieringAzureExternalTargetParams) GetStorageAccountName() string {
	if o == nil || o.StorageAccountName.Get() == nil {
		var ret string
		return ret
	}

	return *o.StorageAccountName.Get()
}

// GetStorageAccountNameOk returns a tuple with the StorageAccountName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TieringAzureExternalTargetParams) GetStorageAccountNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageAccountName.Get(), o.StorageAccountName.IsSet()
}

// SetStorageAccountName sets field value
func (o *TieringAzureExternalTargetParams) SetStorageAccountName(v string) {
	o.StorageAccountName.Set(&v)
}

// GetStorageClass returns the StorageClass field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TieringAzureExternalTargetParams) GetStorageClass() string {
	if o == nil || o.StorageClass.Get() == nil {
		var ret string
		return ret
	}

	return *o.StorageClass.Get()
}

// GetStorageClassOk returns a tuple with the StorageClass field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TieringAzureExternalTargetParams) GetStorageClassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageClass.Get(), o.StorageClass.IsSet()
}

// SetStorageClass sets field value
func (o *TieringAzureExternalTargetParams) SetStorageClass(v string) {
	o.StorageClass.Set(&v)
}

// GetHotBlobParams returns the HotBlobParams field value if set, zero value otherwise.
func (o *TieringAzureExternalTargetParams) GetHotBlobParams() AzureHotBlobParams {
	if o == nil || IsNil(o.HotBlobParams) {
		var ret AzureHotBlobParams
		return ret
	}
	return *o.HotBlobParams
}

// GetHotBlobParamsOk returns a tuple with the HotBlobParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TieringAzureExternalTargetParams) GetHotBlobParamsOk() (*AzureHotBlobParams, bool) {
	if o == nil || IsNil(o.HotBlobParams) {
		return nil, false
	}
	return o.HotBlobParams, true
}

// HasHotBlobParams returns a boolean if a field has been set.
func (o *TieringAzureExternalTargetParams) HasHotBlobParams() bool {
	if o != nil && !IsNil(o.HotBlobParams) {
		return true
	}

	return false
}

// SetHotBlobParams gets a reference to the given AzureHotBlobParams and assigns it to the HotBlobParams field.
func (o *TieringAzureExternalTargetParams) SetHotBlobParams(v AzureHotBlobParams) {
	o.HotBlobParams = &v
}

func (o TieringAzureExternalTargetParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TieringAzureExternalTargetParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ClientId.IsSet() {
		toSerialize["clientId"] = o.ClientId.Get()
	}
	toSerialize["containerName"] = o.ContainerName.Get()
	if o.Region.IsSet() {
		toSerialize["region"] = o.Region.Get()
	}
	if o.StorageAccessKey.IsSet() {
		toSerialize["storageAccessKey"] = o.StorageAccessKey.Get()
	}
	toSerialize["storageAccountName"] = o.StorageAccountName.Get()
	toSerialize["storageClass"] = o.StorageClass.Get()
	if !IsNil(o.HotBlobParams) {
		toSerialize["hotBlobParams"] = o.HotBlobParams
	}
	return toSerialize, nil
}

func (o *TieringAzureExternalTargetParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"containerName",
		"storageAccountName",
		"storageClass",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTieringAzureExternalTargetParams := _TieringAzureExternalTargetParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTieringAzureExternalTargetParams)

	if err != nil {
		return err
	}

	*o = TieringAzureExternalTargetParams(varTieringAzureExternalTargetParams)

	return err
}

type NullableTieringAzureExternalTargetParams struct {
	value *TieringAzureExternalTargetParams
	isSet bool
}

func (v NullableTieringAzureExternalTargetParams) Get() *TieringAzureExternalTargetParams {
	return v.value
}

func (v *NullableTieringAzureExternalTargetParams) Set(val *TieringAzureExternalTargetParams) {
	v.value = val
	v.isSet = true
}

func (v NullableTieringAzureExternalTargetParams) IsSet() bool {
	return v.isSet
}

func (v *NullableTieringAzureExternalTargetParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTieringAzureExternalTargetParams(val *TieringAzureExternalTargetParams) *NullableTieringAzureExternalTargetParams {
	return &NullableTieringAzureExternalTargetParams{value: val, isSet: true}
}

func (v NullableTieringAzureExternalTargetParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTieringAzureExternalTargetParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


