// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgentHostsSummary Agent Hosts
//
// Specifies the list of Agent Hosts.
//
// swagger:model AgentHostsSummary
type AgentHostsSummary struct {

	// Specifies a list of Agent Host summaries.
	AgentHosts []*AgentHostSummary `json:"agentHosts"`
}

// Validate validates this agent hosts summary
func (m *AgentHostsSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAgentHosts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AgentHostsSummary) validateAgentHosts(formats strfmt.Registry) error {
	if swag.IsZero(m.AgentHosts) { // not required
		return nil
	}

	for i := 0; i < len(m.AgentHosts); i++ {
		if swag.IsZero(m.AgentHosts[i]) { // not required
			continue
		}

		if m.AgentHosts[i] != nil {
			if err := m.AgentHosts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("agentHosts" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("agentHosts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this agent hosts summary based on the context it is used
func (m *AgentHostsSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAgentHosts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AgentHostsSummary) contextValidateAgentHosts(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AgentHosts); i++ {

		if m.AgentHosts[i] != nil {

			if swag.IsZero(m.AgentHosts[i]) { // not required
				return nil
			}

			if err := m.AgentHosts[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("agentHosts" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("agentHosts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AgentHostsSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgentHostsSummary) UnmarshalBinary(b []byte) error {
	var res AgentHostsSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
