// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateLSUParams Specifies the parameter to create an LSU.
//
// swagger:model CreateLSUParams
type CreateLSUParams struct {

	// ID of the Cloud Domain that the LSU will be associated with.
	// Note: an LSU can only be associated with either a Storage Domain or a
	// Cloud Domain. If both storageDomainId and cloudDomainId are
	// specified, cloudDomainId will be used.
	//
	CloudDomainID *int64 `json:"cloudDomainId,omitempty"`

	// Specifies the Storage Domain name.
	// Required: true
	// Min Length: 1
	Name string `json:"name"`

	// Specifies the NBU Domain this LSU is associated with.
	// Required: true
	// Min Length: 1
	NbuDomain string `json:"nbuDomain"`

	// ID of the Storage Domain (View Box) that the LSU will be
	// associated with.
	// - For non-tenant users, if no ID is provided, DefaultStorageDomain
	//   will be used.
	// - For tenant users, providing a valid Storage Domain ID is mandatory.
	// Note: an LSU can only be associated with either a Storage Domain
	// or a Cloud Domain. If both storageDomainId and cloudDomainId are
	// specified, cloudDomainId will be used.
	//
	StorageDomainID *int64 `json:"storageDomainId,omitempty"`

	// worm config
	WormConfig *WormConfig `json:"wormConfig,omitempty"`
}

// Validate validates this create l s u params
func (m *CreateLSUParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNbuDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWormConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateLSUParams) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", m.Name, 1); err != nil {
		return err
	}

	return nil
}

func (m *CreateLSUParams) validateNbuDomain(formats strfmt.Registry) error {

	if err := validate.RequiredString("nbuDomain", "body", m.NbuDomain); err != nil {
		return err
	}

	if err := validate.MinLength("nbuDomain", "body", m.NbuDomain, 1); err != nil {
		return err
	}

	return nil
}

func (m *CreateLSUParams) validateWormConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.WormConfig) { // not required
		return nil
	}

	if m.WormConfig != nil {
		if err := m.WormConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wormConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("wormConfig")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create l s u params based on the context it is used
func (m *CreateLSUParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateWormConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateLSUParams) contextValidateWormConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.WormConfig != nil {
		if err := m.WormConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wormConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("wormConfig")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateLSUParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateLSUParams) UnmarshalBinary(b []byte) error {
	var res CreateLSUParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
