// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HeliosProtectionPolicyIdentifier Protection Policy Identifier.
//
// Specifies Protection Policy Identifier.
//
// swagger:model HeliosProtectionPolicyIdentifier
type HeliosProtectionPolicyIdentifier struct {

	// Specifies Protection Policy id.
	ProtectionPolicyID *string `json:"protectionPolicyId,omitempty"`

	// Specifies Protection Policy name.
	ProtectionPolicyName *string `json:"protectionPolicyName,omitempty"`
}

// Validate validates this helios protection policy identifier
func (m *HeliosProtectionPolicyIdentifier) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this helios protection policy identifier based on context it is used
func (m *HeliosProtectionPolicyIdentifier) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HeliosProtectionPolicyIdentifier) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HeliosProtectionPolicyIdentifier) UnmarshalBinary(b []byte) error {
	var res HeliosProtectionPolicyIdentifier
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
