// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// KMSUsageType KMS Usage Type
//
// Specifies the usage type of key management system.
//
// swagger:model KMSUsageType
type KMSUsageType struct {

	// Specifies the usage type of KMS.
	// Enum: ["kArchival","kRpaasArchival"]
	Value string `json:"value,omitempty"`
}

// Validate validates this k m s usage type
func (m *KMSUsageType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var kMSUsageTypeTypeValuePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["kArchival","kRpaasArchival"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		kMSUsageTypeTypeValuePropEnum = append(kMSUsageTypeTypeValuePropEnum, v)
	}
}

const (

	// KMSUsageTypeValueKArchival captures enum value "kArchival"
	KMSUsageTypeValueKArchival string = "kArchival"

	// KMSUsageTypeValueKRpaasArchival captures enum value "kRpaasArchival"
	KMSUsageTypeValueKRpaasArchival string = "kRpaasArchival"
)

// prop value enum
func (m *KMSUsageType) validateValueEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, kMSUsageTypeTypeValuePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *KMSUsageType) validateValue(formats strfmt.Registry) error {
	if swag.IsZero(m.Value) { // not required
		return nil
	}

	// value enum
	if err := m.validateValueEnum("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this k m s usage type based on context it is used
func (m *KMSUsageType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KMSUsageType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KMSUsageType) UnmarshalBinary(b []byte) error {
	var res KMSUsageType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
