// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RecoverGCPPostgreSQLNewSourceConfig Recover GCP PostgreSQL New Source Config.
//
// Specifies the configuration for recovering GCP PostgreSQL database to the new target.
//
// swagger:model RecoverGCPPostgreSQLNewSourceConfig
type RecoverGCPPostgreSQLNewSourceConfig struct {

	// Specifies the target instance where the GCP PostgreSQL database will be recovered.
	// Required: true
	Instance *RecoveryObjectIdentifier `json:"instance"`

	// Specifies the target source details where GCP PostgreSQL database will be recovered. This source id should be a GCP PostgreSQL target service account email id.
	// Required: true
	Source *RecoveryObjectIdentifier `json:"source"`
}

// Validate validates this recover g c p postgre SQL new source config
func (m *RecoverGCPPostgreSQLNewSourceConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInstance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecoverGCPPostgreSQLNewSourceConfig) validateInstance(formats strfmt.Registry) error {

	if err := validate.Required("instance", "body", m.Instance); err != nil {
		return err
	}

	if m.Instance != nil {
		if err := m.Instance.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("instance")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("instance")
			}
			return err
		}
	}

	return nil
}

func (m *RecoverGCPPostgreSQLNewSourceConfig) validateSource(formats strfmt.Registry) error {

	if err := validate.Required("source", "body", m.Source); err != nil {
		return err
	}

	if m.Source != nil {
		if err := m.Source.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this recover g c p postgre SQL new source config based on the context it is used
func (m *RecoverGCPPostgreSQLNewSourceConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInstance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSource(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecoverGCPPostgreSQLNewSourceConfig) contextValidateInstance(ctx context.Context, formats strfmt.Registry) error {

	if m.Instance != nil {
		if err := m.Instance.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("instance")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("instance")
			}
			return err
		}
	}

	return nil
}

func (m *RecoverGCPPostgreSQLNewSourceConfig) contextValidateSource(ctx context.Context, formats strfmt.Registry) error {

	if m.Source != nil {
		if err := m.Source.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RecoverGCPPostgreSQLNewSourceConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecoverGCPPostgreSQLNewSourceConfig) UnmarshalBinary(b []byte) error {
	var res RecoverGCPPostgreSQLNewSourceConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
