// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReplicationObjectsList Specifies the Replication Objects Response.
//
// swagger:model ReplicationObjectsList
type ReplicationObjectsList struct {

	// Specifies a list of Replication Objects.
	ReplicationObjects []*ReplicationObjectDetails `json:"replicationObjects"`
}

// Validate validates this replication objects list
func (m *ReplicationObjectsList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReplicationObjects(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReplicationObjectsList) validateReplicationObjects(formats strfmt.Registry) error {
	if swag.IsZero(m.ReplicationObjects) { // not required
		return nil
	}

	for i := 0; i < len(m.ReplicationObjects); i++ {
		if swag.IsZero(m.ReplicationObjects[i]) { // not required
			continue
		}

		if m.ReplicationObjects[i] != nil {
			if err := m.ReplicationObjects[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("replicationObjects" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("replicationObjects" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this replication objects list based on the context it is used
func (m *ReplicationObjectsList) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateReplicationObjects(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReplicationObjectsList) contextValidateReplicationObjects(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ReplicationObjects); i++ {

		if m.ReplicationObjects[i] != nil {

			if swag.IsZero(m.ReplicationObjects[i]) { // not required
				return nil
			}

			if err := m.ReplicationObjects[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("replicationObjects" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("replicationObjects" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReplicationObjectsList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReplicationObjectsList) UnmarshalBinary(b []byte) error {
	var res ReplicationObjectsList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
