// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RetentionUnits RetentionUnits
//
// Retention Units.
//
// swagger:model RetentionUnits
type RetentionUnits struct {

	// Specifies the retention unit.
	// Enum: ["Days","Weeks","Months","Years"]
	RetentionUnits string `json:"retentionUnits,omitempty"`
}

// Validate validates this retention units
func (m *RetentionUnits) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRetentionUnits(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var retentionUnitsTypeRetentionUnitsPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Days","Weeks","Months","Years"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		retentionUnitsTypeRetentionUnitsPropEnum = append(retentionUnitsTypeRetentionUnitsPropEnum, v)
	}
}

const (

	// RetentionUnitsRetentionUnitsDays captures enum value "Days"
	RetentionUnitsRetentionUnitsDays string = "Days"

	// RetentionUnitsRetentionUnitsWeeks captures enum value "Weeks"
	RetentionUnitsRetentionUnitsWeeks string = "Weeks"

	// RetentionUnitsRetentionUnitsMonths captures enum value "Months"
	RetentionUnitsRetentionUnitsMonths string = "Months"

	// RetentionUnitsRetentionUnitsYears captures enum value "Years"
	RetentionUnitsRetentionUnitsYears string = "Years"
)

// prop value enum
func (m *RetentionUnits) validateRetentionUnitsEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, retentionUnitsTypeRetentionUnitsPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RetentionUnits) validateRetentionUnits(formats strfmt.Registry) error {
	if swag.IsZero(m.RetentionUnits) { // not required
		return nil
	}

	// value enum
	if err := m.validateRetentionUnitsEnum("retentionUnits", "body", m.RetentionUnits); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this retention units based on context it is used
func (m *RetentionUnits) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RetentionUnits) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RetentionUnits) UnmarshalBinary(b []byte) error {
	var res RetentionUnits
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
