// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SalesforceOAuth2Credentials OAuth2 credentials.
//
// # Specifies the credentials to register a Salesforce source
//
// swagger:model SalesforceOAuth2Credentials
type SalesforceOAuth2Credentials struct {

	// Specifies the Client ID for OAuth2 authentication.
	// Required: true
	ClientID *string `json:"clientId"`

	// Specifies the Client Secret for OAuth2 authentication.
	// Required: true
	ClientSecret *string `json:"clientSecret"`
}

// Validate validates this salesforce o auth2 credentials
func (m *SalesforceOAuth2Credentials) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClientSecret(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SalesforceOAuth2Credentials) validateClientID(formats strfmt.Registry) error {

	if err := validate.Required("clientId", "body", m.ClientID); err != nil {
		return err
	}

	return nil
}

func (m *SalesforceOAuth2Credentials) validateClientSecret(formats strfmt.Registry) error {

	if err := validate.Required("clientSecret", "body", m.ClientSecret); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this salesforce o auth2 credentials based on context it is used
func (m *SalesforceOAuth2Credentials) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SalesforceOAuth2Credentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SalesforceOAuth2Credentials) UnmarshalBinary(b []byte) error {
	var res SalesforceOAuth2Credentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
