// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UnRegisterApplicationServersParams un register application servers params
//
// swagger:model UnRegisterApplicationServersParams
type UnRegisterApplicationServersParams struct {

	// Specifies the types of applications such as 'kSQL', 'kExchange', 'kAD' etc. running on the Protection Source.
	ApplicationEnvironments []string `json:"applicationEnvironments"`
}

// Validate validates this un register application servers params
func (m *UnRegisterApplicationServersParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApplicationEnvironments(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var unRegisterApplicationServersParamsApplicationEnvironmentsItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["kVMware","kHyperV","kVCD","kSQL","kView","kRemoteAdapter","kPhysical","kPure","kIbmFlashSystem","kAzure","kNetapp","kGenericNas","kAcropolis","kIsilon","kKVM","kAWS","kAWSNative","kAwsS3","kAWSSnapshotManager","kRDSSnapshotManager","kRDSPostgresSnapshotManager","kRDSMySQLSnapshotManager","kRDSMSSQLSnapshotManager","kRDSOracleSnapshotManager","kRDSMariaDBSnapshotManager","kRDSCustomMSSQLSnapshotManager","kRDSCustomOracleSnapshotManager","kAuroraSnapshotManager","kAuroraPostgresSnapshotManager","kAuroraMySQLSnapshotManager","kAwsRDSPostgresBackup","kAwsRDSPostgres","kAwsAuroraPostgres","kAWSMySQL","kAWSAuroraMySQL","kAwsDynamoDB","kAWSDocumentDB","kAWSRdsOracle","kAWSRDSPostgresDB","kAWSAuroraPostgresDB","kAWSRDSMSSQL","kAWSRedshift","kAzureNative","kAzureSQL","kAzureEntraID","kAzureMySQL","kAzureCosmosDBNoSQL","kAzureCosmosDBMongoDB","kAzureBlobStorage","kAzureCosmosDBCassandra","kAzurePostgreSQLServer","kAzureSQLDB","kAzureSQLMI","kAzureTableStorage","kAzureTableAPI","kAzureSnapshotManager","kExchange","kOracle","kGCP","kGCPBigQuery","kGCPFirestore","kGCPMySQL","kGCPSQLServer","kGCPPostgreSQL","kGCPAlloyDBPostgreSQL","kGoogleSpanner","kGCPBigtable","kFlashBlade","kO365","kHyperFlex","kAD","kGPFS","kKubernetes","kNimble","kElastifile","kCassandra","kMongoDB","kCouchbase","kHdfs","kHive","kHBase","kUDA","kS3Compatible","kSAPHANA","kO365Sharepoint","kO365PublicFolders","kO365Teams","kO365Group","kO365Exchange","kO365OneDrive","kSfdc","kO365ExchangeCSM","kO365OneDriveCSM","kO365SharepointCSM","kExperimentalAdapter","kMongoDBPhysical","kGoogleWorkspace","kGmail","kGoogleDrive","kDB2","kEwsExchange","kServiceNow","kSalesforce","kPostgres","kNutanixFS","kJira","kPinecone"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		unRegisterApplicationServersParamsApplicationEnvironmentsItemsEnum = append(unRegisterApplicationServersParamsApplicationEnvironmentsItemsEnum, v)
	}
}

func (m *UnRegisterApplicationServersParams) validateApplicationEnvironmentsItemsEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, unRegisterApplicationServersParamsApplicationEnvironmentsItemsEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UnRegisterApplicationServersParams) validateApplicationEnvironments(formats strfmt.Registry) error {
	if swag.IsZero(m.ApplicationEnvironments) { // not required
		return nil
	}

	for i := 0; i < len(m.ApplicationEnvironments); i++ {

		// value enum
		if err := m.validateApplicationEnvironmentsItemsEnum("applicationEnvironments"+"."+strconv.Itoa(i), "body", m.ApplicationEnvironments[i]); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this un register application servers params based on context it is used
func (m *UnRegisterApplicationServersParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UnRegisterApplicationServersParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnRegisterApplicationServersParams) UnmarshalBinary(b []byte) error {
	var res UnRegisterApplicationServersParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
