/*
 * Cohesity REST API
 *
 * Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// package helios
package models

import (
	"encoding/json"
	. "github.com/cohesity/go-sdk/helios/utils"
)

var _ = NullableBool{}

// TimeOfDay Specifies the time of day. Used for scheduling purposes.
type TimeOfDay struct {
	// Specifies the hour of the day (0-23).
	Hour NullableInt32 `json:"hour"`
	// Specifies the minute of the hour (0-59).
	Minute NullableInt32 `json:"minute"`
	// Specifies the time zone of the user. If not specified, default value is assumed as America/Los_Angeles.
	TimeZone NullableString `json:"timeZone,omitempty"`
}

// NewTimeOfDay instantiates a new TimeOfDay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeOfDay(hour NullableInt32, minute NullableInt32) *TimeOfDay {
	this := TimeOfDay{}
	this.Hour = hour
	this.Minute = minute
	var timeZone string = "America/Los_Angeles"
	this.TimeZone = *NewNullableString(&timeZone)
	return &this
}

// NewTimeOfDayWithDefaults instantiates a new TimeOfDay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeOfDayWithDefaults() *TimeOfDay {
	this := TimeOfDay{}
	var timeZone string = "America/Los_Angeles"
	this.TimeZone = *NewNullableString(&timeZone) // model_simple false
	return &this
}

// GetHour returns the Hour field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *TimeOfDay) GetHour() int32 {
	if o == nil || o.Hour.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Hour.Get()
}

// GetHourOk returns a tuple with the Hour field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimeOfDay) GetHourOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Hour.Get(), o.Hour.IsSet()
}

// SetHour sets field value
func (o *TimeOfDay) SetHour(v int32) {
	o.Hour.Set(&v)
}

// GetMinute returns the Minute field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *TimeOfDay) GetMinute() int32 {
	if o == nil || o.Minute.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Minute.Get()
}

// GetMinuteOk returns a tuple with the Minute field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimeOfDay) GetMinuteOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Minute.Get(), o.Minute.IsSet()
}

// SetMinute sets field value
func (o *TimeOfDay) SetMinute(v int32) {
	o.Minute.Set(&v)
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TimeOfDay) GetTimeZone() string {
	if o == nil || o.TimeZone.Get() == nil {
		var ret string
		return ret
	}
	return *o.TimeZone.Get()
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TimeOfDay) GetTimeZoneOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.TimeZone.Get(), o.TimeZone.IsSet()
}

// HasTimeZone returns a boolean if a field has been set.
func (o *TimeOfDay) HasTimeZone() bool {
	if o != nil && o.TimeZone.IsSet() {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given NullableString and assigns it to the TimeZone field.
func (o *TimeOfDay) SetTimeZone(v string) {
	o.TimeZone.Set(&v)
}
// SetTimeZoneNil sets the value for TimeZone to be an explicit nil
func (o *TimeOfDay) SetTimeZoneNil() {
	o.TimeZone.Set(nil)
}

// UnsetTimeZone ensures that no value is present for TimeZone, not even an explicit nil
func (o *TimeOfDay) UnsetTimeZone() {
	o.TimeZone.Unset()
}

func (o TimeOfDay) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["hour"] = o.Hour.Get()
	}
	if true {
		toSerialize["minute"] = o.Minute.Get()
	}
	if o.TimeZone.IsSet() {
		toSerialize["timeZone"] = o.TimeZone.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableTimeOfDay struct {
	value *TimeOfDay
	isSet bool
}

func (v NullableTimeOfDay) Get() *TimeOfDay {
	return v.value
}

func (v *NullableTimeOfDay) Set(val *TimeOfDay) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeOfDay) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeOfDay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeOfDay(val *TimeOfDay) *NullableTimeOfDay {
	return &NullableTimeOfDay{value: val, isSet: true}
}

func (v NullableTimeOfDay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeOfDay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


