/*
 * Cohesity REST API
 *
 * Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// package onprem
package models

import (
	"encoding/json"
	. "github.com/cohesity/go-sdk/onprem/utils"
	"fmt"
)

var _ = NullableBool{}

// ProtectionPolicyType Protection Policy Type.
type ProtectionPolicyType struct {
	// Specifies the protection policy type.
	Type *string `json:"type,omitempty"`
}

// NewProtectionPolicyType instantiates a new ProtectionPolicyType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtectionPolicyType() *ProtectionPolicyType {
	this := ProtectionPolicyType{}
	return &this
}

// NewProtectionPolicyTypeWithDefaults instantiates a new ProtectionPolicyType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtectionPolicyTypeWithDefaults() *ProtectionPolicyType {
	this := ProtectionPolicyType{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ProtectionPolicyType) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectionPolicyType) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ProtectionPolicyType) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ProtectionPolicyType) SetType(v string) {
	o.Type = &v
}

func (o ProtectionPolicyType) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableProtectionPolicyType struct {
	value *ProtectionPolicyType
	isSet bool
}

func (v NullableProtectionPolicyType) Get() *ProtectionPolicyType {
	return v.value
}

func (v *NullableProtectionPolicyType) Set(val *ProtectionPolicyType) {
	v.value = val
	v.isSet = true
}

func (v NullableProtectionPolicyType) IsSet() bool {
	return v.isSet
}

func (v *NullableProtectionPolicyType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtectionPolicyType(val *ProtectionPolicyType) *NullableProtectionPolicyType {
	return &NullableProtectionPolicyType{value: val, isSet: true}
}

func (v NullableProtectionPolicyType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtectionPolicyType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}




func (o ProtectionPolicyType) Print() {
		if byteArray, err := o.MarshalJSON(); err != nil {
				fmt.Println(err)
		} else {
				fmt.Println(string(byteArray))
		}
}