/*
 * Cohesity REST API
 *
 * Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// package onprem
package models

import (
	"encoding/json"
	. "github.com/cohesity/go-sdk/onprem/utils"
	"fmt"
)

var _ = NullableBool{}

// NisProviders Response of NIS Providers.
type NisProviders struct {
	// A list of NIS Providers.
	NisProviders []NisProvider `json:"nisProviders,omitempty"`
}

// NewNisProviders instantiates a new NisProviders object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNisProviders() *NisProviders {
	this := NisProviders{}
	return &this
}

// NewNisProvidersWithDefaults instantiates a new NisProviders object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNisProvidersWithDefaults() *NisProviders {
	this := NisProviders{}
	return &this
}

// GetNisProviders returns the NisProviders field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NisProviders) GetNisProviders() []NisProvider {
	if o == nil  {
		var ret []NisProvider
		return ret
	}
	return o.NisProviders
}

// GetNisProvidersOk returns a tuple with the NisProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NisProviders) GetNisProvidersOk() (*[]NisProvider, bool) {
	if o == nil || o.NisProviders == nil {
		return nil, false
	}
	return &o.NisProviders, true
}

// HasNisProviders returns a boolean if a field has been set.
func (o *NisProviders) HasNisProviders() bool {
	if o != nil && o.NisProviders != nil {
		return true
	}

	return false
}

// SetNisProviders gets a reference to the given []NisProvider and assigns it to the NisProviders field.
func (o *NisProviders) SetNisProviders(v []NisProvider) {
	o.NisProviders = v
}

func (o NisProviders) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NisProviders != nil {
		toSerialize["nisProviders"] = o.NisProviders
	}
	return json.Marshal(toSerialize)
}

type NullableNisProviders struct {
	value *NisProviders
	isSet bool
}

func (v NullableNisProviders) Get() *NisProviders {
	return v.value
}

func (v *NullableNisProviders) Set(val *NisProviders) {
	v.value = val
	v.isSet = true
}

func (v NullableNisProviders) IsSet() bool {
	return v.isSet
}

func (v *NullableNisProviders) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNisProviders(val *NisProviders) *NullableNisProviders {
	return &NullableNisProviders{value: val, isSet: true}
}

func (v NullableNisProviders) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNisProviders) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}




func (o NisProviders) Print() {
		if byteArray, err := o.MarshalJSON(); err != nil {
				fmt.Println(err)
		} else {
				fmt.Println(string(byteArray))
		}
}