/*
 * Cohesity REST API
 *
 * Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// package onprem
package models

import (
	"encoding/json"
	. "github.com/cohesity/go-sdk/onprem/utils"
	"fmt"
)

var _ = NullableBool{}

// SharepointObjectEntityParams Specifies the common parameters for Sharepoint site objects.
type SharepointObjectEntityParams struct {
	// Specifies the web url for the Sharepoint site.
	SiteWebUrl NullableString `json:"siteWebUrl,omitempty"`
}

// NewSharepointObjectEntityParams instantiates a new SharepointObjectEntityParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSharepointObjectEntityParams() *SharepointObjectEntityParams {
	this := SharepointObjectEntityParams{}
	return &this
}

// NewSharepointObjectEntityParamsWithDefaults instantiates a new SharepointObjectEntityParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSharepointObjectEntityParamsWithDefaults() *SharepointObjectEntityParams {
	this := SharepointObjectEntityParams{}
	return &this
}

// GetSiteWebUrl returns the SiteWebUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SharepointObjectEntityParams) GetSiteWebUrl() string {
	if o == nil || o.SiteWebUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.SiteWebUrl.Get()
}

// GetSiteWebUrlOk returns a tuple with the SiteWebUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SharepointObjectEntityParams) GetSiteWebUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SiteWebUrl.Get(), o.SiteWebUrl.IsSet()
}

// HasSiteWebUrl returns a boolean if a field has been set.
func (o *SharepointObjectEntityParams) HasSiteWebUrl() bool {
	if o != nil && o.SiteWebUrl.IsSet() {
		return true
	}

	return false
}

// SetSiteWebUrl gets a reference to the given NullableString and assigns it to the SiteWebUrl field.
func (o *SharepointObjectEntityParams) SetSiteWebUrl(v string) {
	o.SiteWebUrl.Set(&v)
}
// SetSiteWebUrlNil sets the value for SiteWebUrl to be an explicit nil
func (o *SharepointObjectEntityParams) SetSiteWebUrlNil() {
	o.SiteWebUrl.Set(nil)
}

// UnsetSiteWebUrl ensures that no value is present for SiteWebUrl, not even an explicit nil
func (o *SharepointObjectEntityParams) UnsetSiteWebUrl() {
	o.SiteWebUrl.Unset()
}

func (o SharepointObjectEntityParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SiteWebUrl.IsSet() {
		toSerialize["siteWebUrl"] = o.SiteWebUrl.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableSharepointObjectEntityParams struct {
	value *SharepointObjectEntityParams
	isSet bool
}

func (v NullableSharepointObjectEntityParams) Get() *SharepointObjectEntityParams {
	return v.value
}

func (v *NullableSharepointObjectEntityParams) Set(val *SharepointObjectEntityParams) {
	v.value = val
	v.isSet = true
}

func (v NullableSharepointObjectEntityParams) IsSet() bool {
	return v.isSet
}

func (v *NullableSharepointObjectEntityParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSharepointObjectEntityParams(val *SharepointObjectEntityParams) *NullableSharepointObjectEntityParams {
	return &NullableSharepointObjectEntityParams{value: val, isSet: true}
}

func (v NullableSharepointObjectEntityParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSharepointObjectEntityParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}




func (o SharepointObjectEntityParams) Print() {
		if byteArray, err := o.MarshalJSON(); err != nil {
				fmt.Println(err)
		} else {
				fmt.Println(string(byteArray))
		}
}