/*
 * Cohesity REST API
 *
 * Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// package onprem
package models

import (
	"encoding/json"
	. "github.com/cohesity/go-sdk/onprem/utils"
	"fmt"
)

var _ = NullableBool{}

// MongoDBProtectionGroupParamsAllOf struct for MongoDBProtectionGroupParamsAllOf
type MongoDBProtectionGroupParamsAllOf struct {
	// Specifies the CDP related information for a given protection group. This field will only be populated when protection group is configured with a CDP policy.
	CdpInfo *MongoDBCdpJobInfo `json:"cdpInfo,omitempty"`
}

// NewMongoDBProtectionGroupParamsAllOf instantiates a new MongoDBProtectionGroupParamsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMongoDBProtectionGroupParamsAllOf() *MongoDBProtectionGroupParamsAllOf {
	this := MongoDBProtectionGroupParamsAllOf{}
	return &this
}

// NewMongoDBProtectionGroupParamsAllOfWithDefaults instantiates a new MongoDBProtectionGroupParamsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMongoDBProtectionGroupParamsAllOfWithDefaults() *MongoDBProtectionGroupParamsAllOf {
	this := MongoDBProtectionGroupParamsAllOf{}
	return &this
}

// GetCdpInfo returns the CdpInfo field value if set, zero value otherwise.
func (o *MongoDBProtectionGroupParamsAllOf) GetCdpInfo() MongoDBCdpJobInfo {
	if o == nil || o.CdpInfo == nil {
		var ret MongoDBCdpJobInfo
		return ret
	}
	return *o.CdpInfo
}

// GetCdpInfoOk returns a tuple with the CdpInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MongoDBProtectionGroupParamsAllOf) GetCdpInfoOk() (*MongoDBCdpJobInfo, bool) {
	if o == nil || o.CdpInfo == nil {
		return nil, false
	}
	return o.CdpInfo, true
}

// HasCdpInfo returns a boolean if a field has been set.
func (o *MongoDBProtectionGroupParamsAllOf) HasCdpInfo() bool {
	if o != nil && o.CdpInfo != nil {
		return true
	}

	return false
}

// SetCdpInfo gets a reference to the given MongoDBCdpJobInfo and assigns it to the CdpInfo field.
func (o *MongoDBProtectionGroupParamsAllOf) SetCdpInfo(v MongoDBCdpJobInfo) {
	o.CdpInfo = &v
}

func (o MongoDBProtectionGroupParamsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CdpInfo != nil {
		toSerialize["cdpInfo"] = o.CdpInfo
	}
	return json.Marshal(toSerialize)
}

type NullableMongoDBProtectionGroupParamsAllOf struct {
	value *MongoDBProtectionGroupParamsAllOf
	isSet bool
}

func (v NullableMongoDBProtectionGroupParamsAllOf) Get() *MongoDBProtectionGroupParamsAllOf {
	return v.value
}

func (v *NullableMongoDBProtectionGroupParamsAllOf) Set(val *MongoDBProtectionGroupParamsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMongoDBProtectionGroupParamsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMongoDBProtectionGroupParamsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMongoDBProtectionGroupParamsAllOf(val *MongoDBProtectionGroupParamsAllOf) *NullableMongoDBProtectionGroupParamsAllOf {
	return &NullableMongoDBProtectionGroupParamsAllOf{value: val, isSet: true}
}

func (v NullableMongoDBProtectionGroupParamsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMongoDBProtectionGroupParamsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}




func (o MongoDBProtectionGroupParamsAllOf) Print() {
		if byteArray, err := o.MarshalJSON(); err != nil {
				fmt.Println(err)
		} else {
				fmt.Println(string(byteArray))
		}
}