/*
 * Cohesity REST API
 *
 * Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// package onprem
package models

import (
	"encoding/json"
	. "github.com/cohesity/go-sdk/onprem/utils"
	"fmt"
)

var _ = NullableBool{}

// ExchangeProtectionGroupObjectParams Specifies the object identifier to for the exchange protection group.
type ExchangeProtectionGroupObjectParams struct {
	// Specifies the id of the registered Exchange DAG(Database Availability Group) source or Exchange physical source.
	Id NullableInt64 `json:"id"`
	// Specifies the name of the registered Exchange DAG(Database Availability Group) source or Exchange physical source.
	Name NullableString `json:"name,omitempty"`
	// Specifies the specific parameters required for Exchange app configuration.
	AppParams []ExchangeAppParams `json:"appParams,omitempty"`
}

// NewExchangeProtectionGroupObjectParams instantiates a new ExchangeProtectionGroupObjectParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExchangeProtectionGroupObjectParams(id NullableInt64) *ExchangeProtectionGroupObjectParams {
	this := ExchangeProtectionGroupObjectParams{}
	this.Id = id
	return &this
}

// NewExchangeProtectionGroupObjectParamsWithDefaults instantiates a new ExchangeProtectionGroupObjectParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExchangeProtectionGroupObjectParamsWithDefaults() *ExchangeProtectionGroupObjectParams {
	this := ExchangeProtectionGroupObjectParams{}
	return &this
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *ExchangeProtectionGroupObjectParams) GetId() int64 {
	if o == nil || o.Id.Get() == nil {
		var ret int64
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExchangeProtectionGroupObjectParams) GetIdOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *ExchangeProtectionGroupObjectParams) SetId(v int64) {
	o.Id.Set(&v)
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExchangeProtectionGroupObjectParams) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExchangeProtectionGroupObjectParams) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ExchangeProtectionGroupObjectParams) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ExchangeProtectionGroupObjectParams) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *ExchangeProtectionGroupObjectParams) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ExchangeProtectionGroupObjectParams) UnsetName() {
	o.Name.Unset()
}

// GetAppParams returns the AppParams field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExchangeProtectionGroupObjectParams) GetAppParams() []ExchangeAppParams {
	if o == nil  {
		var ret []ExchangeAppParams
		return ret
	}
	return o.AppParams
}

// GetAppParamsOk returns a tuple with the AppParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExchangeProtectionGroupObjectParams) GetAppParamsOk() (*[]ExchangeAppParams, bool) {
	if o == nil || o.AppParams == nil {
		return nil, false
	}
	return &o.AppParams, true
}

// HasAppParams returns a boolean if a field has been set.
func (o *ExchangeProtectionGroupObjectParams) HasAppParams() bool {
	if o != nil && o.AppParams != nil {
		return true
	}

	return false
}

// SetAppParams gets a reference to the given []ExchangeAppParams and assigns it to the AppParams field.
func (o *ExchangeProtectionGroupObjectParams) SetAppParams(v []ExchangeAppParams) {
	o.AppParams = v
}

func (o ExchangeProtectionGroupObjectParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.AppParams != nil {
		toSerialize["appParams"] = o.AppParams
	}
	return json.Marshal(toSerialize)
}

type NullableExchangeProtectionGroupObjectParams struct {
	value *ExchangeProtectionGroupObjectParams
	isSet bool
}

func (v NullableExchangeProtectionGroupObjectParams) Get() *ExchangeProtectionGroupObjectParams {
	return v.value
}

func (v *NullableExchangeProtectionGroupObjectParams) Set(val *ExchangeProtectionGroupObjectParams) {
	v.value = val
	v.isSet = true
}

func (v NullableExchangeProtectionGroupObjectParams) IsSet() bool {
	return v.isSet
}

func (v *NullableExchangeProtectionGroupObjectParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExchangeProtectionGroupObjectParams(val *ExchangeProtectionGroupObjectParams) *NullableExchangeProtectionGroupObjectParams {
	return &NullableExchangeProtectionGroupObjectParams{value: val, isSet: true}
}

func (v NullableExchangeProtectionGroupObjectParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExchangeProtectionGroupObjectParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}




func (o ExchangeProtectionGroupObjectParams) Print() {
		if byteArray, err := o.MarshalJSON(); err != nil {
				fmt.Println(err)
		} else {
				fmt.Println(string(byteArray))
		}
}