// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateViewBoxParamsDefaultViewQuotaPolicy Specifies an optional default logical quota limit (in bytes)
// for the Views in this Storage Domain (View Box).
// (Logical data is when the data is fully hydrated and expanded.)
// However, this inherited quota can be overwritten at the View level.
// A new write is not allowed if the Storage Domain (View Box) will exceed
// the specified quota.
// However, it takes time for the Cohesity Cluster to calculate
// the usage across Nodes, so the limit may be exceeded by a small amount.
// In addition, if the limit is increased or data is removed,
// there may be delay before the Cohesity Cluster allows more data
// to be written to the Storage Domain (View Box), as the Cluster is
// calculating the usage across Nodes.
//
// swagger:model createViewBoxParamsDefaultViewQuotaPolicy
type CreateViewBoxParamsDefaultViewQuotaPolicy struct {
	QuotaPolicy
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *CreateViewBoxParamsDefaultViewQuotaPolicy) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 QuotaPolicy
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.QuotaPolicy = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m CreateViewBoxParamsDefaultViewQuotaPolicy) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.QuotaPolicy)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this create view box params default view quota policy
func (m *CreateViewBoxParamsDefaultViewQuotaPolicy) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with QuotaPolicy
	if err := m.QuotaPolicy.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this create view box params default view quota policy based on the context it is used
func (m *CreateViewBoxParamsDefaultViewQuotaPolicy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with QuotaPolicy
	if err := m.QuotaPolicy.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *CreateViewBoxParamsDefaultViewQuotaPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateViewBoxParamsDefaultViewQuotaPolicy) UnmarshalBinary(b []byte) error {
	var res CreateViewBoxParamsDefaultViewQuotaPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
