// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LdapProviderStatus LDAP Provider Status.
//
// LDAP provider status struct.
//
// swagger:model LdapProviderStatus
type LdapProviderStatus struct {

	// Specifies the connection status message of an LDAP provider.
	StatusMessage *string `json:"statusMessage,omitempty"`
}

// Validate validates this ldap provider status
func (m *LdapProviderStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ldap provider status based on context it is used
func (m *LdapProviderStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LdapProviderStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LdapProviderStatus) UnmarshalBinary(b []byte) error {
	var res LdapProviderStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
