// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtectionJobIncrementalProtectionStartTime CBT-based Protection Schedule Start Time.
//
// Specifies the time of day to start the CBT-based Protection Schedule.
// This is optional and only applicable if the Protection Policy defines
// a monthly or a daily CBT-based Protection Schedule.
// Default value is 02:00 AM.
// deprecated: true
//
// swagger:model protectionJobIncrementalProtectionStartTime
type ProtectionJobIncrementalProtectionStartTime struct {
	TimeOfDay
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ProtectionJobIncrementalProtectionStartTime) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TimeOfDay
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TimeOfDay = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ProtectionJobIncrementalProtectionStartTime) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.TimeOfDay)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this protection job incremental protection start time
func (m *ProtectionJobIncrementalProtectionStartTime) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TimeOfDay
	if err := m.TimeOfDay.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this protection job incremental protection start time based on the context it is used
func (m *ProtectionJobIncrementalProtectionStartTime) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TimeOfDay
	if err := m.TimeOfDay.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ProtectionJobIncrementalProtectionStartTime) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtectionJobIncrementalProtectionStartTime) UnmarshalBinary(b []byte) error {
	var res ProtectionJobIncrementalProtectionStartTime
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
