// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StringEntityIdsProtoStringID This is enclosed in a message to give the flexibilty to add more fields in
// future. For eg: software version, date of creation.
//
// swagger:model StringEntityIdsProto_StringId
type StringEntityIdsProtoStringID struct {

	// Unique identifier for the string entity. This field is used to
	// uniquely distinguish different entities within the system.
	ID *string `json:"id,omitempty"`

	// Version number associated with the string id. This can be used to track
	// different versions of the entity id over time. The string ID assigned to
	// the an entity may change (infrequently) across software versions.
	Version *int64 `json:"version,omitempty"`
}

// Validate validates this string entity ids proto string Id
func (m *StringEntityIdsProtoStringID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this string entity ids proto string Id based on context it is used
func (m *StringEntityIdsProtoStringID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StringEntityIdsProtoStringID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StringEntityIdsProtoStringID) UnmarshalBinary(b []byte) error {
	var res StringEntityIdsProtoStringID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
